version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: postgres-aban-tether
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=abantether
      - POSTGRES_USER=vahid
      - POSTGRES_PASSWORD=vahid
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - django

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"
    networks:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-aban-tether
    env_file: .env
    environment:
      - DATABASE_URL=psql://vahid:vahid@db/abantether

    volumes:
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - django
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-aban-tether
    env_file: .env
    environment:
      - DATABASE_URL=psql://vahid:vahid@db/abantether
    depends_on:
      - db
    restart: on-failure
    networks:
      - django
  redis:
    image: redis:7
    container_name: redis-aban-tether
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - django


networks:
  django:


volumes:
    postgres-data:
    redis-data:
    media:

